---
title: "Replication of The Study by Payne et al. (2008, Psychological Science)"
author: "Jinxiao Zhang (jinx.zhang@stanford.edu)"
date: "`r format(Sys.time(), '%Oct %6, %2018')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---
  
*Links to*
[my repo](https://github.com/tepzhang/payne2008), [the experiments demo](http://web.stanford.edu/~jzhang18/psych251/my_tasks/task_learning.html) and [the original paper](https://github.com/tepzhang/payne2008/blob/master/original_paper/Payne%20et%20al.%202008%20PS.pdf)

(Since I have not got stimuli from the authors, the experiment is just a demo using non-original pictures.)

<!-- R pub: http://rpubs.com/jxzhang/psych251  -->

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

##Introduction

  This study by Payne and colleagues is one of the earliest and most cited studies on the effect of sleep on emotional memory. Participants in 4 conditions viewed neutral and negative scences before a recognition test. Participants in the morning 30-min condition and the evening 30-min condition were tested 30 minutes after viewing the scences in the morning and in the evening respectively. Participants in the wake-delay condition viewed the scences in the morning and were tested 12 hours later in the evening with no daytime sleep.  Participants in the sleep-delay condition viewed the scences in the evening and were tested 12 hours later in the morning with night-time sleep. Participants in the morning 30-min condition and the evening 30-min conditions did not differ in their recognition of neutral or negative scenes, suggesting no circadian effect on the memory. However, recognition of negative objects were better recognized in the sleep-delay condition than the wake-delay condition. The recognition of neutral objects or background did not differ between the sleep-delay condition and the wake-delay condition. As there is no circadian effect, I plan to only replicate their finding that sleep specifically enhances memory of emotional objects as compared with an equal time duration of wakefulness.
  
  This replication study will recruit 48 participants to be randomly assigned to either a wake-delay condition or a sleep-delay condition. Participants in the wake-delay condiiton view the stimuli at 9 am and are tested 12 hours later at 9 pm. Participants in the sleep-delay condition view the stimuli at 9 pm and are tested at 9 am. In the learning phase, participants view a set of scences with either a nagetive object (e.g., a car accident) or a neutral object (e.g., an intact car) on a neutral background (e.g., a street). Twelve hours later in the test phase, they are presented with a series of objects and backgrounds one at a time. Some of the objects and backgrounds are identical to those in the learning phase, some of the objects and backgrounds are similar but not identical to those in the learning phase, and others are new objects and backgrounds. For each object or background, participants indicate whether it is identical, similar, or new to those learned 12 hours ago.
  
  There are two major challenges for this replication project. First, the original authors did not share their stimuli with the paper. I need to first contact the authors for the stimuli. If unfortunately I do not get the stimuli from the authors, I need to create a set of picture stimuli by myself. Second, participants may not necessarily comply with the experiment timing requirement. I need to design ways to ensure participants start their 2 phases at the designated time (9 am or 9 pm).

##Methods
###Power Analysis

The original sample size is n=48 with 24 in the wake-delay condition and 24 in the sleep-delay condition. The major result in Payne et al. (2018) is a 2-way within-between interaction with $\eta^2_{p}$ = .20. To detect such effect size ($\eta^2_{p}$ = .20 or equivalently f = .5) with 80% power and an assumed medium correlation = .3 among repeated measures, a total sample size = 14 is required. To achieve 90% and 95% poewr, a total sample size = 18 and 22 is required respectively.

###Planned Sample

Although the power analysis showed that a smaller sample size is needed than the orginal study, in order to strictly replicate the original study, this replication project will recruit 24 participants in the wake-delay condition and 24 participants in the sleep-delay conditions.

###Materials

"The scenes portrayed negative arousing or neutral objects placed on plausible neutral backgrounds. For each of 64 scenes (e.g., a car on a street), we created eight different versions by placing each of two similar neutral objects (e.g., two images of a car) and each of two related negative objects (e.g., two images of a car accident) on each of two plausible neutral backgrounds (e.g., two images of a street). An additional 32 scenes served as lures on a recognition memory test (Fig. 1). Participants in a previous study had rated the objects and backgrounds for valence and arousal, using 7-point scales (Kensinger, Garoff-Eaton, & Schacter, 2006). All negative objects had received arousal ratings of 5 to 7 (with high scores signifying an exciting or arousing image) and valence ratings lower than 3 (with low scores signifying a negative image). All neutral items (objects and backgrounds) had been rated as nonarousing (arousal values lower than 4) and neutral (valence ratings between 3 and 5)." This was followed precisely.

![**Fig. 1.** "Examples of the scenes presented to subjects. Eight versions of each scene were created by combining each of four similar objects (two neutral objects, two negative and arousing emotional objects) with each of two plausible neutral backgrounds. In this example, the two neutral central objects are cars, and the two negative central objects are cars damaged in an accident; the neutral backgrounds are street scenes. Two of the eight versions of the completed scene are shown."](http://journals.sagepub.com/na101/home/literatum/publisher/sage/journals/content/pssa/2008/pssa_19_8/j.1467-9280.2008.02157.x/20160829/images/medium/10.1111_j.1467-9280.2008.02157.x-fig1.gif)

###Procedure	
"Participants studied a set of 64 scenes (32 with a neutral object and 32 with a negative object, all on neutral backgrounds) for 5 s each, and then indicated on a 7-point scale whether they would approach or move away from the scene if they encountered it in real life. This task was used to maximize encoding. The studied version of each scene (of the eight possible versions) was counterbalanced across participants.

After the delay period, participants performed an unexpected, self-paced recognition task. During this task, objects and backgrounds were presented separately and one at a time. Some of these objects and backgrounds were identical to the scene components that had been studied (e.g., the same car accident), others were the alternate version of the object or background and therefore shared the same verbal label but differed in specific visual details (e.g., a similar car accident), and others were objects or backgrounds that had not been studied (new). Participants never saw both the same and the similar version of an item at test. Each object or background was presented with a question (e.g., "Did you see a monkey?"). If the answer to the question was "yes," participants pressed one button to indicate that the object or background was an exact match to a studied component ("same") or a second button to indicate that it was not an exact match ("similar"). If the answer to the question was "no," they pressed a third button.2

The recognition task included 32 same objects (16 negative, 16 neutral), 32 similar objects (16 negative, 16 neutral), 32 new objects (16 negative, 16 neutral), 32 same backgrounds (16 previously shown with a negative object, 16 previously shown with a neutral object), 32 similar backgrounds (16 previously shown with a negative object, 16 previously shown with a neutral object), and 32 new backgrounds." This was followed precisely.

###Analysis Plan

"We scored a response as specific recognition of visual details when a subject correctly responded "same" to a *same* item, but as general recognition without specific details when a subject responded "similar" to a *same* item. Because "similar" responses were constrained by the number of "same" responses (i.e., subjects responded "similar" only when they did not remember the visual details), we computed the general recognition score as the proportion of "similar" responses after exclusion of "same" responses (similar/[1???same])." "Specific and general recognition scores were computed separately for central objects (negative or neutral) and for the peripheral neutral backgrounds (studied with either a negative or a neutral object). " To replicate the results, a 2 (condition: sleep, wake) × 2 (valence: negative, neutral) × 2 (scene component: object, background) mixed ANOVA was applied on general recognition. And planned follow-up 2 (condition: sleep, wake) × 2 (valence: negative, neutral) mixed ANOVA were applied on the recognition of objects and backgrounds separately.

**Clarify key analysis of interest here** A 2 (condition: sleep, wake) × 2 (valence: negative, neutral) × 2 (scene component: object, background) mixed ANOVA was applied on specific recognition. And planned follow-up 2 (condition: sleep, wake) × 2 (valence: negative, neutral) mixed ANOVA were applied on the recognition of objects and backgrounds separately. These analyses were conducted in the original study but no significant 3-way interaction was found.

###Differences from Original Study

This replication project differs from the original study in two major ways. First, the original experiments were run in a laboratory while the current replication experiments were run online. Second, participants in the original study were college students while participants in the current replication study were workers on Amazon Mechanical Turk. These differences were not anticipated to make a difference based on the claim in the original paper that "memory for a negative scene develops differentially across time delays containing sleep and wake, with sleep selectively consolidating those aspects of memory that are of greatest value to the organism."

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or "none".


##Results

### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

A 2 (condition: sleep, wake) × 2 (valence: negative, neutral) × 2 (scene component: object, background) mixed ANOVA on general recognition revleaed a 3-way condition by valence by scene component interaction, ...... As planned, a 2 (condition: sleep, wake) × 2 (valence: negative, neutral) mixed ANOVA on the recognition of objects showed a condition by valence interaction, ...... And a 2 (condition: sleep, wake) × 2 (valence: negative, neutral) mixed ANOVA on the recognition of backgrounds showed no interaction effect, ......

(The analyses as specified in the analysis plan.)

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

A 2 (condition: sleep, wake) × 2 (valence: negative, neutral) × 2 (scene component: object, background) mixed ANOVA on specific recognition showed ......

(Any follow-up analyses desired (not required).) 

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
